language: node_js
node_js:
- 12.5.0
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palette_test;' -U postgres
notifications:
  email: false
deploy:
  api_key:
    secure: FRaBnWtMfd32DMBda4o2TSCk9XkGOY/SzNfTqFa80BbaHqmVk2Z/xCz9dZ/paq3CKF5+XARta/WUEHCHY1ZrsQIH0cMamG8nhUJ2OLd/Hl17Uu/YwkD8+K0V1NpOKke6SGUIt/Vt+C+Bm0NXeoA+VIbMEhAXdxbeNCg3zTqw0RJYi+A9fu9IK/oY6Bj9DeMF+pvJ2DnG57ytjxixcAkLtnpwSMnTG41M7cWJZlMnB/M7YdmiarGn3k9l70O4I/01O3obGHoeuQDYAE6QvX6pj8IYWDwJq+r/OKX4wk17DuVrwo8TSJE/SA1NQFsComoVcNsAZRNZ2KzF3+S3AhrrtXj6LVjMJDnrLdcK5xD5yhywND/9b9mDc3CzLlLAaJEPQafn4wFUTbgYqGwl5A9DkpXw5Fcc3RfRp/Hx9csJUm3EwUBdDB3lo6s+hOWo2oADfGDT4K30qSwCL8qwNRsQXsxRqbw2dJDsUiR5Fu1q3dtQ2ElXZDqedCecfM+u2Y5gRzzOoeWyWKnkUbPskZETfQOl8XzI0WGXkRKurn1cNQaMuu4c8w3rzIW3DAHxuOgZyI+wD0shyPwQ9ofTj+BExzQsFlxBZCV6NwiCPSTdjTcNnjhnVf+nr0UdlGjp8EwvgjMU21Fxr0maexu7LgFRpIloXA9E4NLKW7akX4Yu2Iw=
